name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: test and lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: v1.64.5
